apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: provider-vsphere-helm
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      #- cluster: '1'
      #- cluster: '2'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        applicationset: cluster-deployments
      name: provider-vsphere-helm-{{ cluster }}
    spec:
      destination:
        namespace: provider-vsphere-helm-{{ cluster }}
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        helm:
          valueFiles:
          - values.provider-vsphere-helm-{{ cluster }}.yaml
        path: provider-vsphere/helm
        repoURL: git@github.com:sebastian-colomar/hive-through-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
