apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: provider-aws-ocp-1-worker
  namespace: provider-aws-ocp-1
spec:
  clusterDeploymentRef:
    name: provider-aws-ocp-1
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 3000
        size: 100
        type: gp3
      type: m6a.large
  replicas: 3
