{{- if not .Values.machinepools }}
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: "{{ .Values.cluster.name }}-infra"
  namespace: {{ .Values.cluster.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  labels:
    node-role.kubernetes.io/infra: ""
  name: infra
  platform:
    aws:
      rootVolume:
        iops: 3000
        size: 100
        type: gp3
      type: m6a.large
  replicas: 3
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
{{- end }}
