apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    cluster.open-cluster-management.io/backup: cluster
  name: "{{ .Values.cluster.name }}-pull-secret"
  namespace: {{ .Values.cluster.name }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.cluster.pullSecret }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster.open-cluster-management.io/backup: cluster
      name: "{{ .Values.cluster.name }}-pull-secret"
      namespace: {{ .Values.cluster.name }}
    type: kubernetes.io/dockerconfigjson
