apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: "{{ .Values.cluster.name }}-ssh-privatekey"
  namespace: {{ .Values.cluster.name }}
spec:
  encryptedData:
    ssh-privatekey: {{ .Values.cluster.sshPrivateKey }}
  template:
    metadata:
      creationTimestamp: null
      name: "{{ .Values.cluster.name }}-ssh-privatekey"
      namespace: {{ .Values.cluster.name }}
    type: Opaque

