apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    cluster.open-cluster-management.io/backup: cluster
  name: "{{ .Values.cluster.name }}-install-config"
  namespace: {{ .Values.cluster.name }}
spec:
  encryptedData:
    install-config.yaml: {{ .Values.cluster.installConfig }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster.open-cluster-management.io/backup: cluster
      name: "{{ .Values.cluster.name }}-install-config"
      namespace: {{ .Values.cluster.name }}
    type: Opaque
