apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: vSphere
    cluster.open-cluster-management.io/clusterset: {{ .Values.cluster.clusterset }}
    name: {{ .Values.cluster.name }}
    vendor: OpenShift
  name: {{ .Values.cluster.name }}
spec:
  hubAcceptsClient: true
