apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: "{{ .Values.cluster.name }}-vsphere-certs"
  namespace: {{ .Values.cluster.name }}
spec:
  encryptedData:
    .cacert: {{ .Values.vsphere.cacert }}
  template:
    metadata:
      creationTimestamp: null
      name: "{{ .Values.cluster.name }}-vsphere-certs"
      namespace: {{ .Values.cluster.name }}
    type: Opaque
