apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: "{{ .Values.cluster.name }}-vsphere-creds"
  namespace: {{ .Values.cluster.name }}
spec:
  encryptedData:
    password: {{ .Values.vsphere.password }}
    username: {{ .Values.vsphere.username }}
  template:
    metadata:
      creationTimestamp: null
      name: "{{ .Values.cluster.name }}-vsphere-creds"
      namespace: {{ .Values.cluster.name }}
    type: Opaque
