apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: ocp-sealed-1-infra
  namespace: ocp-sealed-1
spec:
  clusterDeploymentRef:
    name: ocp-sealed-1
  labels:
    node-role.kubernetes.io/infra: ""
  name: infra
  platform:
    aws:
      rootVolume:
        iops: 3000
        size: 100
        type: gp3
      type: m6a.large
  replicas: 3
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
