---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ocp-sealed-1-aws-creds
  namespace: ocp-sealed-1
spec:
  encryptedData:
    aws_access_key_id: AgCOBXh32fK+IEPGkX5U1FY+S6BQCaNPVudwbRPZ08o/4cSLEzuqhc5YlVNGcpgTzjCFxayfOU9wjkyvJB1hXJobOAhfaAskDCq7fpxuGd30cFXlzJAbho6Kmz3rM5/GupUHuzAXl6QKy17QKEjNZX0dyQUDCugiz24b1rG9zRZnzA+oyNQN1/LDvszAxCtbozct2UrXZLKz2B8RbmOLa+sQBpOJ9TbKW0X1LzRlDrcqxX7enPM9krFM/qiQfQ6HciKt7Ndb97wRXy4J8syZri6dXMJtok7FfrsSPC5VrlSN37q7nUuYXcSC8lcBsgwCGFVLCiWxkvPmL22wvOfkKlsNEgBXcW4VC7DPw3gNhkQ4Osz0g8Uf0Q2uzBps4AHZ0fPSdFbWvyBdWloiHrFVNl+BOKCMgKl2+5b7kzqcYQZitP2HuWGQIVYwz8UileMsvSB0r/31J9y/887xD6hffN96zX6uOgGYbKdQYhFAavTmIiOfGiPSN+HlnWC6L0PW2GNAuKK84y/lojWLCE4E81Y5knKJiGYJkJnTI+ZQQguOfHcWCfhzaSWod7w5j+Czo5bY2/yfurmhjjNe5MFT4PtMolhOZtLBsycnQm6yD8Httln5vvQLPKx8rkDXmhcIyc0MGmIU4L40w8FTKV9H2/8BhLinxEcG6KqFyETx8RH50JSxSR/ocsc2tsfpmJizS3NQx650gitxED36H+zSQBuxGwDuDA==
    aws_secret_access_key: AgBRyOGrrv3B2Z3XjLmnCCKeoyF8lwjNAnn0VpB4QGOTeFmbJez6KeNfyVbhCcbOCnDA42LZWAq6eQFwHUF+hHCephoti93VM1ngJXYMOmZxFC7oYk9prqcN7j1v7Z7S9dhH768dzT6bkQC2T/z9j+vJqQ01YueXrIHJseKyvMhkFq42Ios6XnO371eJNill4TYth1bKkSdwcoB4XavM1XZzSwY5+nIsDFYVPws0WTk0NIINciflci/LgR4rmgSFN/b8VA8BBO5/+o3RNigxV5gyeCQ2wH2fOcXT9sn6N/BFTVmyqX9XcGmegRDA1QTsn5Rn7QQyU/aF+pAs4Tbu+KpkueDTLUL9XAjUgXb84a1Sqw4/aO50/RDxI/S1FiG134Puue3YCE/8t1mGGU2a7jDn45KJ9HRkcvggMo1bFCnDFkGQebpB8QhpFQuIyrtvCx8fWEkWaRWNuDEnXojJ7R6u036LfPYq/4DXNlNuY3Atj0W+UyQCjxnwsgIp001zIbKFDjSvIHMO6j+ZChILRI24dy/EfS55THWns4ay9nYlcEE9z6wqYqIVIfxWrqigTOUnCa1RjIxz99DaB4NM4FI//D3xoQdyv5OYXcBx2LSEnuE5Xzlh+9K8rAf2OvrKShSU9Fi26MBjcYBoxvyucf6HikS50SkzHiDl2/0DUgbWn3vicwF5iEm8LPZkO664yK/lFyeHCj0DXePsjOGOt4EhYltdIQ45QSfpXuZcI3vciJ5W+Dk1heU1
  template:
    metadata:
      creationTimestamp: null
      name: ocp-sealed-1-aws-creds
      namespace: ocp-sealed-1
    type: Opaque
