apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  server:
    route:
      enabled: true
