apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-sealed-1
spec:
  destination:
    namespace: helm-sealed-1
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
      - values.helm-sealed-1.yaml
    path: provider-aws/helm-sealed
    repoURL: 'git@github.com:sebastian-colomar/hive.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
