apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-deployments
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: '1'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        applicationset: cluster-deployments
      name: provider-aws-helm-sealed-{{ cluster }}
    spec:
      destination:
        namespace: provider-aws-helm-{{ cluster }}
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        helm:
          valueFiles:
          - values.helm-sealed-{{ cluster }}.yaml
        path: provider-aws/helm-sealed
        repoURL: git@github.com:sebastian-colomar/hive-through-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
