{{- if not .Values.machinepools }}
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: "{{ .Values.cluster.name }}-worker"
  namespace: {{ .Values.cluster.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 3000
        size: 100
        type: gp3
      type: t3a.large
  replicas: 3
{{- end }}
