apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: "{{ .Values.cluster.name }}-aws-creds"
  namespace: {{ .Values.cluster.name }}
spec:
  encryptedData:
    aws_access_key_id: {{ .Values.aws.aws_access_key_id }}
    aws_secret_access_key: {{ .Values.aws.aws_secret_access_key }}
  template:
    metadata:
      creationTimestamp: null
      name: "{{ .Values.cluster.name }}-aws-creds"
      namespace: {{ .Values.cluster.name }}
    type: Opaque

