---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    cluster.open-cluster-management.io/backup: cluster
  name: helm-sealed-1-aws-creds
  namespace: helm-sealed-1
spec:
  encryptedData:
    aws_access_key_id: AgBPDXpvKZ7KPtU6BOFseC1o8Sc6hLF6J68hygWygZtstIwOKHbncOIoOKmNkEWz+0xaCV9m6t44OmKnLQOAPfhtmeBVC1TAGdG73LViYNtZV7imnZd11F3wQSw9j/h7MeUexhYSHU2YYzFpA1oVS5y1jZ0q0VDrjiBuMltqnh8NqjOyinSZdr8PnJYwTHCX+kSPXCspcD1FHBuDxVbhqdPqJaV1cShjbCRF0NFamPoM3+Lx5pnB0N8anhwmzWMK2HEcRSQwEcNRedio0skgyO7CbC7FkKgSvt4qDvkIJAdsfGMGfz7F/KJLpX+O5GfYKvuqZsYIJZn7yhImdoZfBKGyEFMHk07myvLEOVElVY/xGjNHBe3pyVyWRk+AqKJb3oOPi2EMfO9VNZaOEdUqkX+KjqyRW5qIYJQLLg+Wspckk3nwGM85W793m9ePByhBNuiZvH64VRDfeiJWb2saxOfNgwsAtxLMvjGvrrSG4Q+ti9ZHA4Jcdt4EQ4GhNDAWpazRn4sSTlwqVMPmbRIKVJ/VKC38roZNImyymq8rJt5Tu9oeGDw2Imo5ACiUNfKCVW2IkExXEtwrNwYeqVDn6uP3ulyXEpKjPFj0mccR9AEHdX9qqvR+Lw0oGA5gW4z6tcJ2c4e8Kig66RywhcLHfhCb2fvTCB2gnfb5qo1wHr+GgGZa3b779ilitDJ771IIwpfq63P5Wqv5omdrcipofxzBz+epAQ==
    aws_secret_access_key: AgBMIZYcAMhkI9iSZULqbaadwLq0xynI83/d7XJmajyxjtwcDmhyh0FjzbPeXd5M8QEY4wtsAhgmEbLA3KapXR77i1FU+Wgz1Yk+N261u/c809TcYSQJliMxlkGwgqVoz2vndBxdstAzGGRx6JSDdX7qw5DmLVd4ADQ2qnsh6EVHprT7C1jhcg94L/k/1aXIekKks8PMEd3wrRi7AqgI2cBoKIBmAOiRGgC/3AbdfxnWs1slfoooyA2zfrVGe9MHAfSELgW0EBcozvw31jGtWWS2TYDCMs+h1ICkQXC3FsyZi9++U27SrE3IZ5DoprPq3n1osI3UBhkgSM2QauuwqAaFNCtyj/dyaI/M2kVfK/j+N9hAS7V8U0sQM2+KAWf6PUAXHoC0AKzJW+WlzqJxS2/UxekViTDDW5TPy2aNtt2qZwsxoPFYyFPF0Rp3+YGRPhExPmandrCpHccaG11MB2wQztk5jD7pbGmFhcEDIEBXnr3FP2jtnrttBlW9sC736W6tJL+POnQLX/PnA+G/SloZ7/9l4fDNQKkwP6tEdK2/DK4l2cWyhGfa7gSbfNAAll+f4kVMjUC11nspsxKxdtRQ2VXW2s/bspgnZYmVKzWf+KJI3cTEVhQ/Y1Ip8CEJ4fUn8wrVm/aJH12hZuAOAESaX/pa0Xw5+NSaz1kkvdpmW5oKXjpcmTw+hoEp6ziZWFjkr4Qd7nvT1KcNmuCWYX4+gGo3UImmmt+4zNsTDPOe/xtXWrAJWgQa
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster.open-cluster-management.io/backup: cluster
      name: helm-sealed-1-aws-creds
      namespace: helm-sealed-1
    type: Opaque
