apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    cluster.open-cluster-management.io/backup: cluster
    cluster.open-cluster-management.io/copiedFromNamespace: open-cluster-management
    cluster.open-cluster-management.io/copiedFromSecretName: aws-creds
  name: helm-sealed-1-pull-secret
  namespace: helm-sealed-1
stringData:
  .dockerconfigjson: >-
    {"auths":{"cloud.openshift.com":{"auth":"==","email":"sebastian.colomar@gmail.com"},"quay.io":{"auth":"==","email":"sebastian.colomar@gmail.com"},"registry.connect.redhat.com":{"auth":"xxx","email":"sebastian.colomar@gmail.com"},"registry.redhat.io":{"auth":"xxx","email":"sebastian.colomar@gmail.com"}}}
type: kubernetes.io/dockerconfigjson
