apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ocp-sealed-1-ssh-private-key
  namespace: ocp-sealed-1
stringData:
  ssh-privatekey: |-
    -----BEGIN RSA PRIVATE KEY-----
    xx
    -----END RSA PRIVATE KEY-----
type: Opaque
