apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-sealed-1
spec:
  destination:
    namespace: ocp-sealed-1
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: provider-aws/ocp-sealed-1
    repoURL: 'git@github.com:sebastian-colomar/hive-through-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
