apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  finalizers:
  - hive.openshift.io/deprovision
  labels:
    cloud: {{ .Values.cluster.cloud2 }}
    cluster.open-cluster-management.io/clusterset: {{ .Values.cluster.clusterset }}
    hive.openshift.io/cluster-platform: {{ .Values.cluster.platform }}
    vendor: {{ .Values.cluster.vendor }}
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
spec:
  baseDomain: {{ .Values.cluster.baseDomain }}
  clusterName: {{ .Values.cluster.name }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    vsphere:
      certificatesSecretRef:
        name: "{{ .Values.cluster.name }}-{{ .Values.cluster.platform }}-certs"
      cluster: {{ .Values.vsphere.cluster }}
      credentialsSecretRef:
        name: "{{ .Values.cluster.name }}-{{ .Values.cluster.platform }}-creds"
      datacenter: {{ .Values.vsphere.datacenter }}
      defaultDatastore: {{ .Values.vsphere.defaultDatastore }}
      folder: {{ .Values.vsphere.folder }}
      network: {{ .Values.vsphere.network }}
      vCenter: {{ .Values.vsphere.vCenter }}
  provisioning:
    imageSetRef:
      name: {{ .Values.cluster.image }}
    installConfigSecretRef:
      name: "{{ .Values.cluster.name }}-install-config"
    sshPrivateKeySecretRef:
      name: "{{ .Values.cluster.name }}-ssh-private-key"
  pullSecretRef:
    name: "{{ .Values.cluster.name }}-pull-secret"
