{{- if not .Values.machinepools }}
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: "{{ .Values.cluster.name }}-worker"
  namespace: {{ .Values.cluster.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  name: worker
  platform:
    vsphere:
      coresPerSocket: 2
      cpus: 4
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 3
{{- end }}
