apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-aws-ocp-1
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - "*"
  verbs:
  - create
  - delete
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - "*"
  resourceNames:
  - provider-aws-ocp-1
  verbs:
  - create
  - delete
  - patch
- apiGroups:
  - register.open-cluster-management.io
  resources:
  - "*"
  resourceNames:
  - provider-aws-ocp-1
  verbs:
  - update
