aws:
  region: ap-south-1
cluster:
  baseDomain: sebastian-colomar.com
  cloud1: Amazon
  cloud2: AWS
  clusterset: default
  image: img4.16.8-multi-appsub
  name: provider-aws-helm-1
  platform: aws
  vendor: OpenShift
gitops:
  name: openshift-gitops
  namespace: openshift-gitops
machinepools:
  - 
    name: worker
    replicas: 3
    rootVolume:
      iops: 3000
      size: 100
      type: gp3
    type: t3a.large
  - 
    labels:
      node-role.kubernetes.io/infra: ""
    name: infra
    replicas: 3
    rootVolume:
      iops: 3000
      size: 100
      type: gp3
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
    type: t3a.large
