aws:
  region: ap-south-1
cluster:
  baseDomain: sebastian-colomar.com
  cloud1: Amazon
  cloud2: AWS
  clusterset: default
  image: img4.16.8-multi-appsub
  installConfig: AgCULzt0TnFczkKUbJNpEvYF+FWZ67p1R66Vy9NZyuQoBLQuUG5pHUdDAZ6Gf9GN8UCzdRXr3IaNDLzkgvokaaIWH3FhidT8j6A4nfPSGuLIFfNiDhJdeQRBGyGXjvWa1zHe6zKrRmkUDYzWnydTdH3Z0ppYMG2YSL78P2cNfIXY3zRB3LBp72lFEVxwXDiz7g37+T4xVjIbHphraXm4VvwwvvZT6IES9WfBzwU/avEtR8vB2SiJbxwwjfvWMQiZtelKJf6gey9SOgvoq/JPaRazVU4exMOkGmpX2N49sAoHYMrM/kkfXs0ekbf08vJ6Y7TeqI8gehjOktQ/KNhMyd4RC039++9DxohVC8xRRi7Qo4QWDcCgzGANm+uYyS5qe4M0E8MpzJH7FZTZjyAinBWiUKuFb0ndFafReSXRvD6z1Nqjfc6ttWKHea/2IySaP5+lsWiAw+21K0iyRjbLZaOab2PedDn8A4wehmLnlKy2jrfBHb/trcMfyXw7ydq7L1ONR/8RxAChKbiFDpWk2IXcX1Hj7PtT839nB3aMvaX/ZqeW1RTaUBS5A+pm0ged4qKj2xACglBe+VLkvNWExvajPTC0aWeCI37Oe1FPKV8Ip1Lzb2psMz5klytkPq/j8bXT/L9duhXCYq9GjEDfMLDnR3WKKCJJEenCiZGhpEwL+XiegAaFVhXHXXN21RXiAGVWotPd3nbun6r82ADhjhbCeU0RmkW8dGNGaKM9bJ8lkqiFVZiOzkfSfBmb5VoHEvCy0MiJ5QinnOUqSHc057j2sWBGCGHxpusA9GGWKniDZz95H/4Xa3g/yAGBq/fkJsoQw5wAeuSIn5TtX9XfzfSd5gvbXIpwuRVIbM03EvqEo5AHnfbG8K4DN/FT9Xl1dnbmyqvwy7rGksn56uvt4L2NUpQFkHuuEg7j7/MD/9YYfEhoSnKoEroOOdLGWIHIYiaUr0EFu9HCiXYgjrqKLkTkYXfi6CNxirCRYaiAki1vuonkCBN5NdcmvrAfSmQ0S8TCUBDZg48exjQ/knyxgOad+vKQ4BwU6G/YUQZQBY+GmH9Hvba2haRn9I3MuST/kqGjXYj69dSaWafq010Ly3Jg2mUR3S2CPhpJy22mkHuZiOGBy+TUrQSHBYt9jWnUTTvHQIOkw/k92ahoQDXyFlBoSVbNSyZt9gu4L7B5V+EBywLhJ51Gce26+8QPtD1EXgQl0aCsPfI66JqZ9gXgGUnek/QLZqmNXvAwfDZV9192kRhDEHuDhgG7H6cGXnW72s6hXkYidd6Gh7ZGQp2/XfN+7J0EF1DOeGRhoFmKl2E0B+XKswTfkk4o2o5CqmY+QtO8d85yMq8lL0cEEme3GllZZDmEISKSyA7Q22EwjWFewUkPejPOHdAF9/DtB4SFVo8+scz1JD72baXWfDSmYCVQn0XNlqxm8qtkwCyH2MpBbx6Zos+38Kx56b+ukXpmELFMz4ohtx3LdvwTADqpyH5vrKoqc91b1wfPaE9v9EWADulJyg0jEoIXwSavxYumXt22hrTelui6NPRjD5M5zuwQJ/OiULz2p9r916WXEIrx3dEIcSjJqW2M1zfLEJX11sMb9OUw4movaZ951HVxSfXow/rMRE5gK+/L/AQw9jyywrnHCbnX9N81a/1t3p4y3oDAzrHaolM5obkIo29CY/xh4RwQVCRKGoFY5O0lrDHWzcNdsgUxUtAg/Cp7Hdj/5pwW2FFCknHflkDmRwTVjG2zwz/RYA2bFYapuIRz2+f3eNIkQty0Xwrd8ZMLLsSuHQKwq/xXmD3vTIdsoBxi4RqKvPCT+VClwj3O9LWKEKuRUsG6M2t7e1XCSYDvzgsgw0WVUMS5bWs0JAcArlNfgi8BQSjKfE30hEjOM7DTHh3YWkkH7u52vojdegW8QOpbYqdoDV1VQxrPbyPJPasDB7DoeCq2oYC25MHKk07qn0DkKEGN9ADFb62iEiWl/QVzhMwdANYVqkzzSHKSVBX3tlIGzqXpK+60IBnVDHYxU+zodvEICfE7UP4NPCln9u5a40ih5mP7JWxL9KNk+TWu
  name: helm-sealed-1
  platform: aws
  vendor: OpenShift
gitops:
  name: openshift-gitops
  namespace: openshift-gitops
machinepools:
  - 
    name: worker
    replicas: 3
    rootVolume:
      iops: 3000
      size: 100
      type: gp3
    type: t3a.large
  - 
    labels:
      node-role.kubernetes.io/infra: ""
    name: infra
    replicas: 3
    rootVolume:
      iops: 3000
      size: 100
      type: gp3
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
    type: t3a.large
