apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-phpinfo
  namespace: openshift-gitops
stringData:
  name: phpinfo
  project: default
  type: git
  url: https://github.com/sebastian-colomar/phpinfo
type: Opaque
