apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: openshift-gitops-operator-group
  namespace: openshift-gitops-operator
spec:
  upgradeStrategy: Default
