apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: hub-local-cluster
  namespace: open-cluster-management-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          local-cluster: "true"
