apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-deployments
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
        - cluster: ocpl-dc2
  template:
    metadata:
      labels:
        applicationset: cluster-deployments
      name: 'cluster-deployment-{{ cluster }}'
    spec:
      destination:
        name: local-cluster
        namespace: '{{ cluster }}'
      project: default
      source:
        path: helm
        repoURL: git@github.com:academiaonline-org/hive-through-gitops.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.{{ cluster }}.yaml
      syncPolicy:
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
